server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://rm-2zeqd93op69crr9f2ao.mysql.rds.aliyuncs.com:3306/ipush
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ipush
    password: ENC(WkINcAMIjjqTN8Wi+CWxQqJ4C2iyZpUY)

ipush:
  token:
    secret: ENC(bvk3eCYI3r7v9XaXGHdKNG/ACEl8it34)
    expiration: 1800000
    header: ipushToken

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

