server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://rm-2zeqd93op69crr9f2ao.mysql.rds.aliyuncs.com:3306/ipush
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ipush
    password: ENC(WkINcAMIjjqTN8Wi+CWxQqJ4C2iyZpUY)
  mail:
    host: smtp.gmail.com
    nickname: 嘿
    username: cloudinfopush@gmail.com
    password: ENC(THP8jH4MhI+5AVJ5dZGFK1WqUEFBmOcanX+dvfivtbA=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info

